### ISSUE TITLE
Front-end - Service info page

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/eggsroyale-frontend#12]

**Comment by dlouise64** [comment]
![Screen Shot 2018-06-06 at 9.44.49 am.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5d4e54c8f9d70012f9078a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f56b7191a371f1162f4f5b565efd1c4a4356bcbbd671f3e57862804e0ebfd06b0922c63819f9ee8a1fee01ba21df1ed3b7e9db4ad2f42f67b6d5db1063474f4dcbed5727a19141c95df443e34e50a5113e61e2722431.png)

**Comment by dlouise64** [comment]
closes #51

**Comment by Br3nda** [comment]
I think this was closed in #21
