### ISSUE TITLE
Front-end - Home page

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/eggsroyale-frontend#7]
Buttons should link to their pages

**Comment by dlouise64** [comment]
[Uploading Screen Shot 2018-06-06 at 9.37.44 am.png...]

**Comment by dlouise64** [comment]
![Screen Shot 2018-06-06 at 9.37.44 am.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5d4e54c8f9d70012f9078a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f56b7191a371f1112c4f5b5b5efd1c4a4356bcbbd671f3e57862804e0ebfd06b0922c63819f9ee8a1fee01ba21df1ed3b7e9db4ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df443e34e51ac10356ae7712431.png)

**Comment by dlouise64** [comment]
@ssibbehh how can I get these icons in SVG format?

**Comment by ssibbehh** [comment]
@dlouise64 I used Font Awesome for these icons :)

**Comment by dlouise64** [comment]
@ssibbehh excellent thanks!
